### ISSUE TITLE
Hyperlink don't warp at short width

### ISSUE THREAD

**Issue by shirok1** [hitszlug/bilberry-hugo-theme#1]
![image](https://user-images.githubusercontent.com/12044683/158131745-18277ded-63b2-46c9-a01e-6a76133c11d5.png)

Expected:
![image](https://user-images.githubusercontent.com/12044683/158131838-fbf2f873-7e74-48c2-abd4-1d9b1ed9d304.png)

To solve:
```css
.bilberry-hugo-theme a{
  word-wrap: break-word;
}
```

https://github.com/hitszlug/weekly/blob/21e93cda59790809e4180cc77b6f2f90fac10a22/static/css/custom.css#L15
